Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.notesTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.profilesTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: profileId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: profileId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.postsTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: postId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: postId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  # ProductsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.productsTable}
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: S
  #       - AttributeName: productId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #       - AttributeName: productId
  #         KeyType: RANGE
  #     # Set the capacity based on the stage
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}